version: '3.8'  # Always declare the version for explicit compatibility

services:
  app:
    container_name: spring-boot-container
    hostname: localhost
    networks:
      - app-network
    depends_on:
      - db
    build:
      context: ./spring-boot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
