services:
  app:
    container_name: spring-boot-container
    hostname: localhost
    networks:
      - backend-network
    depends_on:
      - postgres
    build:
      context: ./spring-boot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
volumes:
  postgres-data:
networks:
  backend-network:
    driver: bridge
