name: Backend CI
run-name: "Backend CI: ${{ github.ref_name }} by ${{ github.actor }}"

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'temurin'
            cache-dependency-path: backend/pom.xml
            cache: 'maven'

      - name: Add .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Start Google Cloud SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          instance: decoded-carport-440920-j9:europe-west3:thutorium-db

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v4.1.1
        with:
          directory: ./backend